<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="C100-189s-iMac.local" name="newmaven.Tests.errorMessageValidations" tests="7" failures="1" timestamp="2022-10-20T10:06:21 IST" time="55.467" errors="0">
  <testcase name="productMatchValidation" time="5.235" classname="newmaven.Tests.errorMessageValidations"/>
  <system-out/>
  <testcase name="loginError" time="4.043" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <system-out/>
  <testcase name="loginError" time="3.470" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <system-out/>
  <testcase name="loginError" time="3.419" classname="newmaven.Tests.errorMessageValidations">
    <failure type="java.lang.AssertionError" message="expected:&lt;Incorrect email password.&gt; but was:&lt;Incorrect email or password.&gt;">
      <![CDATA[java.lang.AssertionError: expected:<Incorrect email password.> but was:<Incorrect email or password.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at newmaven.Tests.errorMessageValidations.loginError(errorMessageValidations.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- loginError -->
  <system-out/>
  <testcase name="loginError" time="3.445" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <system-out/>
  <testcase name="loginError" time="32.292" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <system-out/>
  <testcase name="loginError" time="3.563" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <system-out/>
</testsuite> <!-- newmaven.Tests.errorMessageValidations -->
